config:
    input_path: "C:\\Users\\vimurali\\ML\\Disaster-Classification\\input"
    processed_io_path: "C:\\Users\\vimurali\\ML\\Disaster-Classification\\processed_io"
    output_path: "C:\\Users\\vimurali\\ML\\Disaster-Classification\\output"
    internal_output_path: "C:\\Users\\vimurali\\ML\\Disaster-Classification\\output\\internal_output"
    visualizations_path: "C:\\Users\\vimurali\\ML\\Disaster-Classification\\visualizations"
    experimental_output_path: "C:\\Users\\vimurali\\ML\\Disaster-Classification\\experimental_logs"


model_args:
    model: 'ann'
    batch_size: 1000
    num_epochs: 10
    lr: 0.001


preproc_args:
    train_validation_split: 0.9